name: 'masterマージ時に自動でtag発行し、Pythonをビルドする'

# このワークフローが実行されるタイミングの定義
on:
  # push時に実行
  push:
    # 対象ブランチ
    branches:
      - master
#  # プルリクエストがマージされた時に実行
#  pull_request:
#    # 対象ブランチ
#    branches:
#      - main

# GitHub Actionsで行うジョブの定義
jobs:
  create-new-tag:
    # Windows環境で実行
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    # 実際のジョブ内容を記載
    steps:
      - name: Branchのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

