name: 'masterマージ時に自動でtag発行'

# このワークフローが実行されるタイミングの定義
on:
  # push時に実行
  push:
    # 対象ブランチ
    branches:
      - master
#  # プルリクエストがマージされた時に実行
#  pull_request:
#    # 対象ブランチ
#    branches:
#      - main

# GitHub Actionsで行うジョブの定義
jobs:
  build:
    # Ubuntu
    runs-on: ubuntu-latest # windows-latest
    # 実際のジョブ内容を記載
    steps:
      - name: Branchのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: タグの発行
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          REPO_OWNER: nnahito
